[package]
name = "licensor_fetch"
version = "0.2.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0.13"
licensor_common = { path = "../licensor_common" }
reqwest = "0.11.7"
sha3 = "0.8.2"
tar = "0.4.26"
